dag_id: get_followers
endpoint: instagram/scrapFollowersOrSimilarAccounts/
info:
  accounts:
  - Booksybiz
  - Wahlpro
  - Titanbarber
  - Official cuts
  - Unitedbyshorthair
  - Behindthechair
  - Ruelrockstar
  - Underratedbarbers
  - Humblythegreatest
  - Arodpr23
  - Phillipwolf
  get_followers: 1
schedule_interval: 10 10 29 1 *
