dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-04-23 12:11:57.465687+00:00
  dag_id: scrapUsersInfoInsertEnrichTheCutThree
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: adf
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: -Nw9reoSZHjhjdvK8_R0
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 10 8 5 4 *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  updated_at: 2024-04-23 12:11:57.465724+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-04-23 12:11:23.879652+00:00
  data:
    chain: true
    index: 0
    query:
    - psychologistswithoutborders
    round: 11
  deleted_at: null
  endpoint: instagram/scrapUsers/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rXdTHJCimoWGvR8g
  log_response: true
  method: POST
  response_check: ''
  task_id: getUsers
  updated_at: 2024-04-23 12:11:23.879678+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 12:11:27.505686+00:00
  data:
    accounts: 18
    chain: true
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 11
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rYMLqvGVWqtdCAKU
  log_response: true
  method: POST
  response_check: ''
  task_id: getInfo
  updated_at: 2024-04-23 12:11:27.505729+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 12:11:30.336211+00:00
  data:
    chain: true
    keywords_to_check:
    - psychologists
    round: 11
  deleted_at: null
  endpoint: instagram/insertAndEnrich/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rZFob_GX9eZUXKtw
  log_response: true
  method: POST
  response_check: ''
  task_id: enrich
  updated_at: 2024-04-23 12:11:30.336246+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 12:11:33.607599+00:00
  data:
    num_tasks: ''
    start_hour: 3
    start_minute: 30
    tasks_per_day: 24
  deleted_at: null
  endpoint: /v1/outreaches/tasks/reschedule_all/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rZzDl2XuiIjqkf8h
  log_response: true
  method: POST
  response_check: ''
  task_id: reschedule
  updated_at: 2024-04-23 12:11:33.607643+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 12:11:36.576852+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getMediaIds/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9r_jC2aSPLfR2bmKG
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaIds
  updated_at: 2024-04-23 12:11:36.576891+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-04-23 12:11:40.115952+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rabCVCxAzstYD9_N
  log_response: true
  method: POST
  response_check: ''
  task_id: like
  updated_at: 2024-04-23 12:11:40.115989+00:00
  url: https://mqtt.booksy.us.boostedchat.com/like
  xcom_push: true
- created_at: 2024-04-23 12:11:42.720757+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getMediaComments/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rbFoFYp_oDo2FtMo
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaComments
  updated_at: 2024-04-23 12:11:42.720822+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-04-23 12:11:45.587040+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rbwIWgQ8hzXLu1Nx
  log_response: true
  method: POST
  response_check: ''
  task_id: comment
  updated_at: 2024-04-23 12:11:45.587051+00:00
  url: https://mqtt.booksy.us.boostedchat.com/comment
  xcom_push: true
- created_at: 2024-04-23 12:11:48.556977+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getAccounts/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rcga5uJ_RiQJoeY4
  log_response: true
  method: POST
  response_check: ''
  task_id: getAccounts
  updated_at: 2024-04-23 12:11:48.556995+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 12:11:52.448377+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9rdSbMR31cloBzUeh
  log_response: true
  method: POST
  response_check: ''
  task_id: reactToStory
  updated_at: 2024-04-23 12:11:52.448413+00:00
  url: https://mqtt.booksy.us.boostedchat.com/reactToStory
  xcom_push: true
