dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-04-23 10:49:41.201358+00:00
  dag_id: scrapUsersInfoInsertEnrichTheCutThree
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: adf
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: -Nw9ZpgUtfZ_V4gXKaA1
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 10 8 5 4 *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  updated_at: 2024-04-23 10:49:41.201422+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-04-23 10:49:10.582312+00:00
  data:
    chain: true
    index: 0
    query:
    - psychologistswithoutborders
    round: 11
  deleted_at: null
  endpoint: instagram/scrapUsers/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZiG3dg30QkfNdyiH
  log_response: true
  method: POST
  response_check: ''
  task_id: getUsers
  updated_at: 2024-04-23 10:49:10.582388+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 10:49:13.239715+00:00
  data:
    accounts: 18
    chain: true
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 11
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9Ziv2ggWau2Q3nXi6
  log_response: true
  method: POST
  response_check: ''
  task_id: getInfo
  updated_at: 2024-04-23 10:49:13.239756+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 10:49:18.673085+00:00
  data:
    chain: true
    keywords_to_check:
    - psychologists
    round: 11
  deleted_at: null
  endpoint: instagram/insertAndEnrich/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZkD4yOYHvXC7PtjI
  log_response: true
  method: POST
  response_check: ''
  task_id: enrich
  updated_at: 2024-04-23 10:49:18.673142+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 10:49:21.188531+00:00
  data:
    num_tasks: ''
    start_hour: 3
    start_minute: 30
    tasks_per_day: 24
  deleted_at: null
  endpoint: /v1/outreaches/tasks/reschedule_all/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZkqFkUrheekyvGx2
  log_response: true
  method: POST
  response_check: ''
  task_id: reschedule
  updated_at: 2024-04-23 10:49:21.188545+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 10:49:23.999665+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getMediaIds/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZlWGjia52U402Mdc
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaIds
  updated_at: 2024-04-23 10:49:23.999720+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-04-23 10:49:26.767032+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZmD4rDXfI67wvv2I
  log_response: true
  method: POST
  response_check: ''
  task_id: like
  updated_at: 2024-04-23 10:49:26.767069+00:00
  url: https://mqtt.booksy.us.boostedchat.com/like
  xcom_push: true
- created_at: 2024-04-23 10:49:29.835560+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getMediaComments/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZmvuuW-KGQFdXi7N
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaComments
  updated_at: 2024-04-23 10:49:29.835598+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-04-23 10:49:32.798634+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZngiZYhP_YYwioKT
  log_response: true
  method: POST
  response_check: ''
  task_id: comment
  updated_at: 2024-04-23 10:49:32.798661+00:00
  url: https://mqtt.booksy.us.boostedchat.com/comment
  xcom_push: true
- created_at: 2024-04-23 10:49:35.364727+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getAccounts/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZoJTxTcy2MoKPcP0
  log_response: true
  method: POST
  response_check: ''
  task_id: getAccounts
  updated_at: 2024-04-23 10:49:35.364786+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 10:49:38.028268+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw9ZoyV3jKUGfiuXx3e
  log_response: true
  method: POST
  response_check: ''
  task_id: reactToStory
  updated_at: 2024-04-23 10:49:38.028334+00:00
  url: https://mqtt.booksy.us.boostedchat.com/reactToStory
  xcom_push: true
