dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-04-24 11:17:29.014207+00:00
  dag_id: scrapUsersInfoInsertEnrichTheCutThree
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: adf
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: -NwEomc2C3u-yeENvbg-
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 10 8 5 4 *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  updated_at: 2024-04-24 11:17:29.014242+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-04-24 11:16:54.608841+00:00
  data:
    chain: true
    index: 0
    query:
    - psychologistswithoutborders
    round: 11
  deleted_at: null
  endpoint: instagram/scrapUsers/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEoeDvimEKx93oOTLg
  log_response: true
  method: POST
  response_check: ''
  task_id: getUsers
  updated_at: 2024-04-24 11:16:54.608860+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-24 11:16:58.413971+00:00
  data:
    accounts: 18
    chain: true
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 11
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEof74UMaxxwsy-hHW
  log_response: true
  method: POST
  response_check: ''
  task_id: getInfo
  updated_at: 2024-04-24 11:16:58.414009+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-24 11:17:01.776865+00:00
  data:
    chain: true
    keywords_to_check:
    - psychologists
    round: 11
  deleted_at: null
  endpoint: instagram/insertAndEnrich/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEofyVcWsIyslGO7sP
  log_response: true
  method: POST
  response_check: ''
  task_id: enrich
  updated_at: 2024-04-24 11:17:01.776945+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-24 11:17:04.951339+00:00
  data:
    num_tasks: ''
    start_hour: 3
    start_minute: 30
    tasks_per_day: 24
  deleted_at: null
  endpoint: /v1/outreaches/tasks/reschedule_all/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEogkV_Ao1tXTF7mKV
  log_response: true
  method: POST
  response_check: ''
  task_id: reschedule
  updated_at: 2024-04-24 11:17:04.951376+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-24 11:17:08.534547+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getMediaIds/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEohc3YHqtg4zbnW2r
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaIds
  updated_at: 2024-04-24 11:17:08.534580+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-04-24 11:17:11.918499+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEoiRrLjvYt-1ddUGk
  log_response: true
  method: POST
  response_check: ''
  task_id: like
  updated_at: 2024-04-24 11:17:11.918534+00:00
  url: https://mqtt.booksy.us.boostedchat.com/like
  xcom_push: true
- created_at: 2024-04-24 11:17:15.910900+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getMediaComments/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEojP_PDjJ5fTZoaro
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaComments
  updated_at: 2024-04-24 11:17:15.910937+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-04-24 11:17:19.286250+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEokF2Xo9r9IvSU6bB
  log_response: true
  method: POST
  response_check: ''
  task_id: comment
  updated_at: 2024-04-24 11:17:19.286268+00:00
  url: https://mqtt.booksy.us.boostedchat.com/comment
  xcom_push: true
- created_at: 2024-04-24 11:17:22.486840+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getAccounts/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEol2FGLt53vmIlHFf
  log_response: true
  method: POST
  response_check: ''
  task_id: getAccounts
  updated_at: 2024-04-24 11:17:22.486877+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-24 11:17:25.737264+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwEolnpjjtdTTXTfa3j
  log_response: true
  method: POST
  response_check: ''
  task_id: reactToStory
  updated_at: 2024-04-24 11:17:25.737295+00:00
  url: https://mqtt.booksy.us.boostedchat.com/reactToStory
  xcom_push: true
