dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-04-23 07:51:54.490375+00:00
  dag_id: scrapUsersInfoInsertEnrichTheCutThree
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: adf
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: -Nw8w8Sv2b8erZ7YG7GD
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 10 8 5 4 *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  updated_at: 2024-04-23 07:51:54.490411+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-04-23 07:51:18.856148+00:00
  data:
    chain: true
    index: 0
    query:
    - psychologistswithoutborders
    round: 11
  deleted_at: null
  endpoint: instagram/scrapUsers/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w-l7AIzZKthGuDTP
  log_response: true
  method: POST
  response_check: ''
  task_id: getUsers
  updated_at: 2024-04-23 07:51:18.856183+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 07:51:22.328062+00:00
  data:
    accounts: 18
    chain: true
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 11
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w0ejVhhZsfiqzFUz
  log_response: true
  method: POST
  response_check: ''
  task_id: getInfo
  updated_at: 2024-04-23 07:51:22.328100+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 07:51:25.921254+00:00
  data:
    chain: true
    keywords_to_check:
    - psychologists
    round: 11
  deleted_at: null
  endpoint: instagram/insertAndEnrich/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w1W7umGPFO8XVwfh
  log_response: true
  method: POST
  response_check: ''
  task_id: enrich
  updated_at: 2024-04-23 07:51:25.921292+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 07:51:29.483447+00:00
  data:
    num_tasks: ''
    start_hour: 3
    start_minute: 30
    tasks_per_day: 24
  deleted_at: null
  endpoint: /v1/outreaches/tasks/reschedule_all/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w2Q1ouxcVimwb0Dp
  log_response: true
  method: POST
  response_check: ''
  task_id: reschedule
  updated_at: 2024-04-23 07:51:29.483485+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 07:51:32.986816+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getMediaIds/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w3EVso8CG2Viu_b8
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaIds
  updated_at: 2024-04-23 07:51:32.986857+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-04-23 07:51:36.570283+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w486mpiG2sHVXBS1
  log_response: true
  method: POST
  response_check: ''
  task_id: like
  updated_at: 2024-04-23 07:51:36.570319+00:00
  url: https://mqtt.booksy.us.boostedchat.com/like
  xcom_push: true
- created_at: 2024-04-23 07:51:40.158818+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getMediaComments/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w507r_TcieJ1Mp3B
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaComments
  updated_at: 2024-04-23 07:51:40.158880+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-04-23 07:51:43.417611+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w5oJTZEF-8O0OfLC
  log_response: true
  method: POST
  response_check: ''
  task_id: comment
  updated_at: 2024-04-23 07:51:43.417649+00:00
  url: https://mqtt.booksy.us.boostedchat.com/comment
  xcom_push: true
- created_at: 2024-04-23 07:51:47.322410+00:00
  data:
    chain: true
    index: 0
    round: 11
  deleted_at: null
  endpoint: instagram/getAccounts/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w6gJh5ebwp6epDR_
  log_response: true
  method: POST
  response_check: ''
  task_id: getAccounts
  updated_at: 2024-04-23 07:51:47.322448+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-04-23 07:51:50.906358+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -Nw8w7d6one9Ceo0HmYl
  log_response: true
  method: POST
  response_check: ''
  task_id: reactToStory
  updated_at: 2024-04-23 07:51:50.906398+00:00
  url: https://mqtt.booksy.us.boostedchat.com/reactToStory
  xcom_push: true
