dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-05-02 08:55:40.270302+00:00
  dag_id: scrapTheCutCoreOutreachWorkflow
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: adf
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: -NwsW2HxmUfgLRcHPTb-
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 10 8 5 4 *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  updated_at: 2024-05-02 08:55:40.270339+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-05-02 08:55:25.627443+00:00
  data:
    chain: true
    index: 0
    query:
    - The Deluxe Cut
    round: 111
  deleted_at: null
  endpoint: instagram/scrapUsers/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwsVzjiRExYlHIqDzhD
  log_response: true
  method: POST
  response_check: ''
  task_id: getUsers
  updated_at: 2024-05-02 08:55:25.627478+00:00
  urls: null
  xcom_push: false
- created_at: 2024-05-02 08:55:28.925106+00:00
  data:
    accounts: 18
    chain: true
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 121
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwsW-XvpVFgFvQXa0NR
  log_response: true
  method: POST
  response_check: ''
  task_id: getInfo
  updated_at: 2024-05-02 08:55:28.925141+00:00
  urls: null
  xcom_push: false
- created_at: 2024-05-02 08:55:31.843463+00:00
  data:
    chain: true
    keywords_to_check:
    - hair
    - appointment
    - appointments
    - book
    - call
    - book.thecut.co
    - licensed
    - cutz
    - kutz
    - cuts
    - cut
    - hairstylist
    - salon
    - salons
    - educator
    - specialist
    - beauty
    - barber
    - walk
    - text
    - stylist
    - colour
    - colouring
    - loreal
    - olaplex
    - hairspray
    - mousse
    - pomade
    - hair oil
    - hair serum
    - scissors
    - comb
    - brush
    - blow dryer
    - flat iron
    - curling iron
    - hair rollers
    - hair clips
    - hair ties
    - headbands
    - hair accessories
    - updos
    - braids
    - twists
    - buns
    - ponytails
    - curls
    - waves
    - volume
    - texture
    - shine
    - frizz control
    - breakage
    - dryness
    - oiliness
    - thinning
    - hair loss
    - dandruff
    - scalp problems
    round: 12
  deleted_at: null
  endpoint: instagram/insertAndEnrich/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwsW0HwrvlugdW1VwRr
  log_response: true
  method: POST
  response_check: ''
  task_id: enrich
  updated_at: 2024-05-02 08:55:31.843496+00:00
  urls: null
  xcom_push: false
- created_at: 2024-05-02 08:55:34.468749+00:00
  data:
    chain: true
    index: 0
    round: 12
  deleted_at: null
  endpoint: instagram/getAccounts/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwsW0vbq8aqGvLrq1vR
  log_response: true
  method: POST
  response_check: ''
  task_id: getAccounts
  updated_at: 2024-05-02 08:55:34.468786+00:00
  urls: null
  xcom_push: false
- created_at: 2024-05-02 08:55:37.350030+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwsW1aRz5xqj_MqNq-n
  log_response: true
  method: POST
  response_check: ''
  task_id: reactToStory
  updated_at: 2024-05-02 08:55:37.350068+00:00
  urls:
  - '{"url": "https://mqtt.booksy.us.boostedchat.com/like", "delay": 105}'
  - '{"url": "https://mqtt.booksy.us.boostedchat.com/comment", "delay": 60}'
  - '{"url": "https://mqtt.booksy.us.boostedchat.com/reactToStory", "delay": 230}'
  xcom_push: true
