dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-05-01 12:44:21.495088+00:00
  dag_id: scrapTheCutCoreOutreachWorkflow
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: adf
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: -NwoAnTmUo4pzBzE9qH7
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 10 8 5 4 *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  updated_at: 2024-05-01 12:44:21.495104+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-05-01 12:43:54.969337+00:00
  data:
    chain: true
    index: 0
    query:
    - The Deluxe Cut
    round: 111
  deleted_at: null
  endpoint: instagram/scrapUsers/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAh0qUb1k-bP7fZIM
  log_response: true
  method: POST
  response_check: ''
  task_id: getUsers
  updated_at: 2024-05-01 12:43:54.969375+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-05-01 12:43:57.724616+00:00
  data:
    accounts: 18
    chain: true
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 121
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAhfFMHmteGJhb5hn
  log_response: true
  method: POST
  response_check: ''
  task_id: getInfo
  updated_at: 2024-05-01 12:43:57.724649+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-05-01 12:44:00.368429+00:00
  data:
    chain: true
    keywords_to_check:
    - hair
    - appointment
    - appointments
    - book
    - call
    - book.thecut.co
    - licensed
    - cutz
    - kutz
    - cuts
    - cut
    - hairstylist
    - salon
    - salons
    - educator
    - specialist
    - beauty
    - barber
    - walk
    - text
    - stylist
    - colour
    - colouring
    - loreal
    - olaplex
    - hairspray
    - mousse
    - pomade
    - hair oil
    - hair serum
    - scissors
    - comb
    - brush
    - blow dryer
    - flat iron
    - curling iron
    - hair rollers
    - hair clips
    - hair ties
    - headbands
    - hair accessories
    - updos
    - braids
    - twists
    - buns
    - ponytails
    - curls
    - waves
    - volume
    - texture
    - shine
    - frizz control
    - breakage
    - dryness
    - oiliness
    - thinning
    - hair loss
    - dandruff
    - scalp problems
    round: 12
  deleted_at: null
  endpoint: instagram/insertAndEnrich/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAiLSXFr00CNH96x4
  log_response: true
  method: POST
  response_check: ''
  task_id: enrich
  updated_at: 2024-05-01 12:44:00.368481+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-05-01 12:44:03.356903+00:00
  data:
    num_tasks: ''
    start_hour: 3
    start_minute: 30
    tasks_per_day: 24
  deleted_at: null
  endpoint: /v1/outreaches/tasks/reschedule_all/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: api_conn
  id: -NwoAj0ehwUwJrQcpp75
  log_response: true
  method: POST
  response_check: ''
  task_id: reschedule
  updated_at: 2024-05-01 12:44:03.356937+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-05-01 12:44:06.121756+00:00
  data:
    chain: true
    index: 0
    round: 12
  deleted_at: null
  endpoint: instagram/getMediaIds/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAjgq3tXEgHQS99xY
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaIds
  updated_at: 2024-05-01 12:44:06.121791+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-05-01 12:44:08.681343+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAkLgp2aR4HZvBb38
  log_response: true
  method: POST
  response_check: ''
  task_id: like
  updated_at: 2024-05-01 12:44:08.681378+00:00
  url: https://mqtt.booksy.us.boostedchat.com/like
  xcom_push: true
- created_at: 2024-05-01 12:44:11.119128+00:00
  data:
    chain: true
    index: 0
    round: 12
  deleted_at: null
  endpoint: instagram/getMediaComments/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAkyS3rWYchqCNNi0
  log_response: true
  method: POST
  response_check: ''
  task_id: getMediaComments
  updated_at: 2024-05-01 12:44:11.119137+00:00
  url: https://example.com
  xcom_push: true
- created_at: 2024-05-01 12:44:13.578676+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAlZqQohuJm1IcCLT
  log_response: true
  method: POST
  response_check: ''
  task_id: comment
  updated_at: 2024-05-01 12:44:13.578711+00:00
  url: https://mqtt.booksy.us.boostedchat.com/comment
  xcom_push: true
- created_at: 2024-05-01 12:44:16.126062+00:00
  data:
    chain: true
    index: 0
    round: 12
  deleted_at: null
  endpoint: instagram/getAccounts/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAmBq5Z59iOspjMzr
  log_response: true
  method: POST
  response_check: ''
  task_id: getAccounts
  updated_at: 2024-05-01 12:44:16.126080+00:00
  url: https://example.com
  xcom_push: false
- created_at: 2024-05-01 12:44:18.818699+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NwoAmqQcCc6Zvq2u2L_
  log_response: true
  method: POST
  response_check: ''
  task_id: reactToStory
  updated_at: 2024-05-01 12:44:18.818740+00:00
  url: https://mqtt.booksy.us.boostedchat.com/reactToStory
  xcom_push: true
